# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 1, 20, 15, 24, 19, 950326)),
        ),
    ]
