# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160120_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 1, 20, 15, 36, 35, 443375)),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(default='', max_length=30),
        ),
    ]
