# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160121_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persontopm',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 1, 24, 6, 0, 41, 931461)),
        ),
    ]
