# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160124_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 1, 24, 6, 1, 43, 440101)),
        ),
    ]
