# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171203_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 12, 3, 6, 46, 11, 264794)),
        ),
    ]
