# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171203_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 12, 3, 6, 50, 30, 601811)),
        ),
    ]
