# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171203_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 17, 55, 44, 994922)),
        ),
    ]
