# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180215_0708'),
        ('app', '0014_auto_20180301_1523'),
    ]

    operations = [
    ]
