# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20180302_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2018, 3, 2, 18, 39, 46, 185300)),
        ),
    ]
