# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180302_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2018, 3, 4, 19, 56, 49, 522492)),
        ),
    ]
