# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180304_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2018, 3, 5, 14, 6, 8, 484908)),
        ),
    ]
