# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180305_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2018, 3, 10, 6, 35, 50, 959660)),
        ),
    ]
