# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180310_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.DateField(default=datetime.datetime(2018, 3, 10, 7, 29, 37, 762432)),
        ),
    ]
